// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB99E0vZrpox-8R7rj79gcMlDJ5VfLWyE',
    appId: '1:677900581774:android:d1bfca6f8b3e1bde6682df',
    messagingSenderId: '677900581774',
    projectId: 'cidadeintegra',
    storageBucket: 'cidadeintegra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhR3gMsY8l96X_rhP5TJ2wkCCxmWhYrOY',
    appId: '1:677900581774:ios:16f7a4086667d8c56682df',
    messagingSenderId: '677900581774',
    projectId: 'cidadeintegra',
    storageBucket: 'cidadeintegra.firebasestorage.app',
    androidClientId: '677900581774-oncsr2ug6aha394cnat7kdhtjs7q190c.apps.googleusercontent.com',
    iosClientId: '677900581774-gkv6jaulqiumtaib14m0ntmjkvbj9k7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.cidadeIntegra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhR3gMsY8l96X_rhP5TJ2wkCCxmWhYrOY',
    appId: '1:677900581774:ios:16f7a4086667d8c56682df',
    messagingSenderId: '677900581774',
    projectId: 'cidadeintegra',
    storageBucket: 'cidadeintegra.firebasestorage.app',
    androidClientId: '677900581774-oncsr2ug6aha394cnat7kdhtjs7q190c.apps.googleusercontent.com',
    iosClientId: '677900581774-gkv6jaulqiumtaib14m0ntmjkvbj9k7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.cidadeIntegra',
  );

}